title: Your Site's Title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write a short description of your site here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kirandwiv.github.io" # the base hostname & protocol for your site
github_username:  kirandwiv

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed